[theme]
base = "light"
primaryColor = "#0078d4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1f1f1f"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false